services:
  cache-pubsub:
    image: valkey/valkey:8.1-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-cache-pubsub
    command: [ "valkey-server", "--save", "", "--appendonly", "no", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru" ]
    restart: always
    volumes:
      - cache-data:/data

volumes:
  cache-data:
    name: ${COMPOSE_PROJECT_NAME}-cache-data
