[workspace]
resolver = "3"
members = ["common", "users"]

[workspace.package]
license = "MIT"

[workspace.dependencies]
# Members
common = { path = "common" }
users = { path = "users" }

# Networking
axum = "0.8.4"
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }
