include:
  - api-docs/compose.yml
services:
  db:
    ports:
      - "5432:5432"
  migrator:
    volumes:
      - ./db/flyway.dev.toml:/flyway/conf/flyway.toml:ro
  cache-pubsub:
    ports:
      - "6379:6379"
  users:
    ports:
      - "8081:8080"
    build:
      args:
        PROFILE: dev
    volumes:
      - ./logs/:/app/logs
  songs:
    ports:
      - "8082:8080"
    build:
      args:
        PROFILE: dev
    volumes:
      - ./logs/:/app/logs
  songs-youtube:
    ports:
      - "8091:8080"
    build:
      args:
        PROFILE: dev
    volumes:
      - ./logs/:/app/logs
  queues:
    ports:
      - "8083:8080"
    build:
      args:
        PROFILE: dev
    volumes:
      - ./logs/:/app/logs
  queues-events:
    ports:
      - "8085:8080"
    build:
      args:
        PROFILE: dev
    volumes:
      - ./logs/:/app/logs
  configs:
    ports:
      - "8084:8080"
    build:
      args:
        PROFILE: dev
    volumes:
      - ./logs/:/app/logs
  gateway:
    ports:
      - "8080:8080"
