services:
  gateway:
    image: nginx:1.27-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-gateway
    restart: always
    volumes:
      - ./nginx:/etc/nginx:ro
    depends_on:
      users:
        condition: service_started
      songs:
        condition: service_started
      queues:
        condition: service_started
