services:
  gateway:
    image: nginx:1.27-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - users
      - songs
