events {
}

http {
    include inbound/upstreams.conf;

    upstream front_service {
        server front:3000;
    }

    server {
        listen 8080;

        include inbound/locations.conf;
        include outbound/locations.conf;


        # Frontend
        location / {
            # No auth request, those are static files

            proxy_pass http://front_service;
        }
    }
}