---
openapi: 3.1.0
info:
  title: Apelle API
  description: |-
    > A communist music queue

    `apelle` is a backend for handling a shared music queue. 
    Users can insert songs in the queues, and upvote them to push them upward. `apelle`
    will track the position of each song in the queue, and the position of the currently
    playing song.

    It also fetch the song data from the sources (for now, only Youtube is supported).
    Users provides only the minimal necessary to identify the song (e.g. the youtube video ID).
  contact:
    name: zannabianca1997
    email: zannabianca199712@gmail.com
  license:
    name: MIT
    url: https://opensource.org/license/mit
