# Program configuration
apelle:
  queue:
    user:
      roles:
        # The role that will be given by default to every user in any queue
        default: VOTER
        # The role of the creator of the queue
        creator: PLAYER
        # The role of banned users
        banned: OBSERVER
        # Config of the roles
        roles:
          PLAYER:
            max-likes: 32000
            permissions:
              queue:
                start: true
                stop: true
                next: true
                like: true
                enqueue: true
                remove: true
                ban: true
              queue-users:
                grant-roles: PLAYER,VOTER,OBSERVER
                remove-roles: VOTER,OBSERVER
                remove: true
                ban: true
          VOTER:
            max-likes: 4
            permissions:
              queue:
                like: true
                enqueue: true
          OBSERVER:
            max-likes: 0
  songs:
    sources:
      youtube:
        api-uri: &yt-api https://www.googleapis.com/youtube/v3
        watch-uri: https://www.youtube.com/watch

# Quarkus configuration
quarkus:
  # Database: the application for now support only PostgreSQL
  datasource:
    db-kind: postgresql
  # Run basic globally
  http:
    auth:
      basic: true
  rest:
    path: /api/v1
  # External APIs urls
  rest-client:
    youtube-api:
      url: *yt-api
  # Configuration of the Swagger
  smallrye-openapi:
    info-version: ${quarkus.application.version}
    store-schema-directory: src/main/webui/openapi
    store-schema-file-name: apelle
  swagger-ui:
    deep-linking: true
  # Frontend integration
  quinoa:
    build-dir: build
    enable-spa-routing: true
    package-manager-command:
      build-env:
        VITE_QUARKUS_PROFILE: ${quarkus.profile}
      dev-env:
        VITE_QUARKUS_PROFILE: ${quarkus.profile}
  hibernate-orm:
    database:
      generation: none
    sql-load-script: no-file
  flyway:
    migrate-at-start: true
  redis:
    configure-client-name: true
    client-name: ${quarkus.application.name:apelle}
