quarkus:
  swagger-ui:
    always-include: true
  quinoa:
    ci: true
  log:
    category:
      "io.github.zannabianca1997.apelle":
        level: DEBUG
      "io.github.zannabianca1997.apelle.queues.utils.QueueEventBus":
        level: INFO # Do not spam each event
