quarkus:
  flyway:
    baseline-on-migrate: true
  rest-client:
    youtube-api:
      # Do not contact youtube during tests
      url:
  log:
    category:
      "io.github.zannabianca1997.apelle":
        level: DEBUG
