services:
  queues-events:
    container_name: ${COMPOSE_PROJECT_NAME}-queues-events
    restart: always
    depends_on:
      queues:
        condition: service_started
      cache-pubsub:
        condition: service_started
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile.rust
      args:
        SERVICE: queues-events
