name: apelle-dev

services:
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-apelle}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-apelle}
      POSTGRES_DB: ${POSTGRES_DB:-apelle}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
