services:
  songs-youtube:
    container_name: ${COMPOSE_PROJECT_NAME}-songs-youtube
    restart: always
    environment:
      APELLE__YOUTUBE__API_KEY: ${YOUTUBE_API_KEY?"The youtube api key must be set"}
    depends_on:
      db:
        condition: service_started
      migrator:
        condition: service_completed_successfully
      cache-pubsub:
        condition: service_started
      songs:
        condition: service_started
      gateway:
        condition: service_started
    build:
      context: ../../..
      dockerfile: ./docker/Dockerfile.rust
      args:
        SERVICE: songs-youtube
