services:
  queues:
    container_name: ${COMPOSE_PROJECT_NAME}-queues
    restart: always
    environment:
      APELLE__DB_URL: ${DB_URL?"The database url must be set"}
      APELLE__CACHE_URL: ${CACHE_URL?"The cache url must be set"}
      APELLE__SONGS_URL: ${SONGS_URL?"The songs service url must be set"}
      APELLE__CONFIGS_URL: ${CONFIGS_URL?"The configs service url must be set"}
    depends_on:
      songs:
        condition: service_started
      users:
        condition: service_started
      db:
        condition: service_started
      migrator:
        condition: service_completed_successfully
      cache-pubsub:
        condition: service_started
      configs:
        condition: service_started
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.rust
      args:
        SERVICE: queues
