services:
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-apelle}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-apelle}
      POSTGRES_DB: ${DB_NAME:-${DB_USER:-apelle}}
    volumes:
      - db-data:/var/lib/postgresql/data

  migrator:
    image: zannabianca1997/${COMPOSE_PROJECT_NAME}-migrator
    container_name: ${COMPOSE_PROJECT_NAME}-migrator
    restart: no
    depends_on:
      db:
        condition: service_started
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.rust
      args:
        SERVICE: migrator

volumes:
  db-data:
    name: ${COMPOSE_PROJECT_NAME}-db-data
