services:
  configs:
    container_name: ${COMPOSE_PROJECT_NAME}-configs
    restart: always
    depends_on:
      db:
        condition: service_started
      migrator:
        condition: service_completed_successfully
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.rust
      args:
        SERVICE: configs
