[package]
name = "apelle-users"
version = "0.1.0"
edition = "2024"

license.workspace = true

[dependencies]
apelle_common.workspace = true

axum.workspace = true
tokio.workspace = true
serde.workspace = true

clap.workspace = true

url.workspace = true

snafu.workspace = true
