services:
  users:
    container_name: ${COMPOSE_PROJECT_NAME}-users
    restart: always
    environment:
      APELLE__DB_URL: ${DB_URL?"The database url must be set"}
    depends_on:
      - db
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.rust
      args:
        SERVICE: users
