include:
  - providers/youtube/compose.yml
services:
  songs:
    container_name: ${COMPOSE_PROJECT_NAME}-songs
    restart: always
    depends_on:
      db:
        condition: service_started
      migrator:
        condition: service_completed_successfully
      cache-pubsub:
        condition: service_started
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.rust
      args:
        SERVICE: songs
