include:
  - providers/youtube/compose.yml
services:
  songs:
    container_name: ${COMPOSE_PROJECT_NAME}-songs
    restart: always
    environment:
      APELLE__DB_URL: ${DB_URL?"The database url must be set"}
      APELLE__CACHE_URL: ${CACHE_URL?"The cache url must be set"}
    depends_on:
      - db
      - cache-pubsub
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.rust
      args:
        SERVICE: songs
